name: Test application

env:
  PYTHON_VERSION: '3.11'         
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  FUNCTION_STR: ${{secrets.FUNCTION_STR}}
  CONNECT_STR: ${{secrets.CONNECT_STR}}

on:
  pull_request:
    branches: [ "main", "beta" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test application
        run: python -m pytest test_app.py
